spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    datasource:
        url: jdbc:mysql://localhost:3306/td
        name: prod
        username: root
        password: qwe123qwe
        hikari:
                    data-source-properties:
                        cachePrepStmts: true
                        prepStmtCacheSize: 250
                        prepStmtCacheSqlLimit: 2048
                        useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show_sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: true
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory


server:
    port: 8080

