spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:mysql://localhost:3306/td
        name: dev
        username: root
        password: qwe123qwe
        hikari:
                    data-source-properties:
                        cachePrepStmts: true
                        prepStmtCacheSize: 250
                        prepStmtCacheSqlLimit: 2048
                        useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        persistenceUnitName: DEV-RBO
        properties:
            hibernate.generate_statistics: "true"
            hibernate.use_sql_comments: "true"
            hibernate.format_sql: "true"
            hibernate.show_sql: "true"
            hibernate.enable_lazy_load_no_trans: "true"
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data
    thymeleaf.cache: false

server:
    port: 8081

