spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        name: dev
        username: sa
        password: sa
        hikari:
                    data-source-properties:
                        cachePrepStmts: true
                        prepStmtCacheSize: 250
                        prepStmtCacheSqlLimit: 2048
                        useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        persistenceUnitName: DEV-RBO
        properties:
            #hibernate.generate_statistics: "true"
            hibernate.use_sql_comments: "true"
            hibernate.format_sql: "true"
            hibernate.show_sql: "true"
            hibernate.hbm2ddl.auto: "create"
    thymeleaf:
         cache: "false"
    mail:
      host: localhost
      port: 25
      username:
      password:
loggining:
    level.: "DEBUG"
metric:
  host: 127.0.0.1
  reportFrequency: 30
  enabled: true
  prometheus:
    enabled: true
    endPoint: /metric
server:
    port: 8081

